# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: zlaval
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Budapest
          plugin_achievements: false
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_ignored: c++, JavaScript, HTML, TypeScript, PHP
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 9417843
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_lines: 2
          plugin_followup: yes
          plugin_followup_indepth: yes